echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.0.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.0.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.0.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.0.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.1.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.1.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.1.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.1.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.2.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.2.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.2.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.2.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.3.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.3.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.3.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.3.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.4.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.4.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.4.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.4.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.5.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.5.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.5.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.5.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.6.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.6.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.6.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.6.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.7.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.7.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.7.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.7.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.8.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.8.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.8.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.8.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.9.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.9.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.9.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.9.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.10.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.10.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.10.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.10.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.11.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.11.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.11.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.11.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.12.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.12.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.12.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.12.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.13.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.13.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.13.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.13.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.14.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.14.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.14.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.14.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.15.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.15.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.15.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.15.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.16.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.16.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.16.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.16.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.17.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.17.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.17.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.17.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.18.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.18.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.18.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.18.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.19.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.19.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.19.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.19.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.20.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.20.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.20.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.20.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.21.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.21.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.21.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.21.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.22.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.22.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.22.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.22.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.23.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.23.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.23.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.23.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.24.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.24.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.24.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.24.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.25.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.25.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.25.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.25.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.26.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.26.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.26.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.26.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.27.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.27.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.27.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.27.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.28.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.28.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.28.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.28.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.29.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.29.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.29.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.29.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.30.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.30.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.30.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.30.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.31.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.31.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.31.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.31.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.32.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.32.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.32.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.32.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.33.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.33.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.33.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.33.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.34.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.34.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.34.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.34.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.35.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.35.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.35.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.35.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.36.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.36.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.36.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.36.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.37.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.37.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.37.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.37.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.38.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.38.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.38.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.38.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.39.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.39.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.39.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.39.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.40.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.40.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.40.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.40.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.41.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.41.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.41.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.41.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.42.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.42.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.42.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.42.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.43.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.43.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.43.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.43.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.44.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.44.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.44.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.44.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.45.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.45.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.45.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.45.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.46.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.46.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.46.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.46.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.47.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.47.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.47.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.47.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.48.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.48.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.48.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.48.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.49.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.49.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.49.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.49.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.50.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.50.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.50.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.50.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.51.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.51.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.51.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.51.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.52.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.52.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.52.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.52.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.53.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.53.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.53.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.53.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.54.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.54.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.54.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.54.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.55.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.55.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.55.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.55.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.56.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.56.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.56.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.56.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.57.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.57.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.57.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.57.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.58.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.58.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.58.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.58.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.59.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.59.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.59.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.59.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.60.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.60.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.60.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.60.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.61.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.61.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.61.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.61.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.62.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.62.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.62.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.62.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.63.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.63.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.63.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.63.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.64.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.64.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.64.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.64.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.65.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.65.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.65.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.65.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.66.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.66.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.66.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.66.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.67.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.67.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.67.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.67.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.68.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.68.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.68.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.68.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.69.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.69.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.69.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.69.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.70.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.70.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.70.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.70.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.71.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.71.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.71.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.71.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.72.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.72.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.72.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.72.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.73.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.73.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.73.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.73.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.74.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.74.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.74.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.74.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.75.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.75.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.75.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.75.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.76.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.76.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.76.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.76.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.77.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.77.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.77.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.77.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.78.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.78.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.78.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.78.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.79.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.79.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.79.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.79.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.80.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.80.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.80.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.80.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.81.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.81.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.81.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.81.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.82.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.82.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.82.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.82.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.83.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.83.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.83.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.83.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.84.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.84.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.84.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.84.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.85.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.85.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.85.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.85.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.86.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.86.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.86.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.86.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.87.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.87.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.87.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.87.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.88.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.88.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.88.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.88.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.89.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.89.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.89.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.89.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.90.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.90.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.90.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.90.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.91.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.91.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.91.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.91.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.92.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.92.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.92.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.92.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.93.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.93.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.93.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.93.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.94.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.94.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.94.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.94.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.95.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.95.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.95.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.95.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.96.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.96.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.96.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.96.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.97.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.97.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.97.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.97.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.98.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.98.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.98.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.98.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.99.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.99.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.99.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.99.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.100.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.100.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.100.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.100.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.101.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.101.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.101.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.101.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.102.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.102.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.102.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.102.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.103.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.103.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.103.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.103.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.104.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.104.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.104.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.104.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.105.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.105.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.105.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.105.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.106.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.106.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.106.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.106.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.107.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.107.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.107.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.107.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.108.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.108.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.108.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.108.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.109.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.109.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.109.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.109.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.110.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.110.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.110.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.110.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.111.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.111.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.111.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.111.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.112.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.112.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.112.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.112.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.113.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.113.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.113.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.113.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.114.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.114.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.114.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.114.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.115.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.115.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.115.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.115.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.116.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.116.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.116.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.116.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.117.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.117.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.117.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.117.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.118.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.118.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.118.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.118.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.119.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.119.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.119.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.119.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.120.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.120.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.120.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.120.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.121.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.121.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.121.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.121.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.122.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.122.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.122.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.122.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.123.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.123.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.123.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.123.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.124.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.124.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.124.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.124.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.125.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.125.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.125.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.125.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.126.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.126.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.126.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.126.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.127.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.127.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.127.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.127.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.128.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.128.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.128.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.128.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.129.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.129.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.129.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.129.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.130.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.130.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.130.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.130.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.131.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.131.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.131.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.131.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.132.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.132.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.132.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.132.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.133.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.133.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.133.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.133.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.134.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.134.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.134.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.134.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.135.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.135.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.135.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.135.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.136.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.136.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.136.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.136.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.137.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.137.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.137.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.137.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.138.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.138.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.138.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.138.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.139.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.139.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.139.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.139.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.140.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.140.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.140.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.140.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.141.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.141.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.141.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.141.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.142.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.142.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.142.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.142.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.143.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.143.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.143.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.143.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.144.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.144.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.144.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.144.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.145.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.145.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.145.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.145.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.146.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.146.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.146.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.146.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.147.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.147.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.147.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.147.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.148.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.148.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.148.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.148.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.149.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.149.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.149.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.149.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.150.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.150.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.150.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.150.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.151.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.151.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.151.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.151.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.152.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.152.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.152.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.152.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.153.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.153.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.153.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.153.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.154.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.154.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.154.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.154.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.155.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.155.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.155.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.155.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.156.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.156.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.156.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.156.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.157.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.157.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.157.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.157.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.158.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.158.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.158.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.158.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.159.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.159.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.159.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.159.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.160.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.160.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.160.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.160.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.161.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.161.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.161.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.161.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.162.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.162.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.162.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.162.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.163.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.163.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.163.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.163.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.164.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.164.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.164.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.164.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.165.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.165.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.165.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.165.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.166.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.166.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.166.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.166.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.167.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.167.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.167.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.167.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.168.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.168.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.168.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.168.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.169.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.169.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.169.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.169.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.170.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.170.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.170.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.170.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.171.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.171.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.171.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.171.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.172.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.172.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.172.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.172.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.173.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.173.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.173.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.173.dis;
echo "disass: gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.174.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.174.dis";
gdb /usr/bin/vim.tiny -x dataexch/disassembly/vim.tiny/cfg/disassemble_vim.tiny_functions.174.cfg >> dataexch/disassembly/vim.tiny/exp/func_disass.174.dis;
